### ISSUE TITLE
idk? its broken

### ISSUE THREAD

**Issue by ElfKing94** [AquUpd/BrownBear#9]
mod doesnt work anymore, it says it updated 2-5 days ago and its the only mod left i cant get working even by itself. theres no previous version history or way to load a previous version. i can give a crash report

**Comment by Ivan-Khar** [comment]
Post the crash log, I'll look into that

**Comment by ElfKing94** [comment]
[crash-2022-08-20_08.23.03-client.txt](https://github.com/Ivan-Khar/GrizzlyBearMob/files/9387290/crash-2022-08-20_08.23.03-client.txt)

**Comment by ElfKing94** [comment]
thanks, hopefully i did everything correctly, also exit code -1 if that helps

**Comment by Ivan-Khar** [comment]
Oh, yeah, I think I just forgot to update the mod to 1.19.2, I'll try to fix it today

**Comment by Ivan-Khar** [comment]
Hello! Can you please check if this version works now? https://modrinth.com/mod/grizzly-bear/version/1.19.2-1.3 
I think I fixed the issue and there shouldn't be any crashes right now, but I cant test it properly rn

**Comment by ElfKing94** [comment]
sure thing! one moment please

**Comment by ElfKing94** [comment]
i have to say its back working again for me, that was fast and you made it look easy, thank you!

**Comment by Ivan-Khar** [comment]
yeah, no problem!

**Comment by ElfKing94** [comment]
hi, i hate to recomment, but i think only that download file you've given here is the only version of this file working for some reason. iv been tinkering with it all morning before work, as when i tried playing it again with other mods and by itself again it would still crash. oddly this file directly from you is fine even with another grizzly bear mod. ill do some more testing with it later when im off, but just letting you know in case others may find this issue. thanks. i didnt want to comment 15 minutes later without first dissecting my issue better

**Comment by Ivan-Khar** [comment]
Make sure that you download 1.19.2 version of the mod instead of 1.19
